# Generated by Django 4.1.1 on 2024-04-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('English_App', '0031_alter_addhomework_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcoursemodel',
            name='courseImage',
            field=models.ImageField(default='default_image.jpg', upload_to='images/%y'),
        ),
        migrations.AddField(
            model_name='addcoursemodel',
            name='instructorImage',
            field=models.ImageField(default='default_image.jpg', upload_to='images/%y'),
        ),
    ]
