# Generated by Django 4.1.1 on 2024-04-20 19:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('English_App', '0032_addcoursemodel_courseimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCourseModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=50)),
                ('courseBody', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('courseImage', models.ImageField(default='default_image.jpg', upload_to='images/%y')),
                ('instructorImage', models.ImageField(default='default_image.jpg', upload_to='images/%y')),
            ],
        ),
    ]
